# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/f2/catkin_ws_h/src/pcl_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/f2/catkin_ws_h/src/pcl_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f2/catkin_ws_h/src/pcl_test/CMakeFiles /home/f2/catkin_ws_h/src/pcl_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f2/catkin_ws_h/src/pcl_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greedy_projection

# Build rule for target.
greedy_projection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greedy_projection
.PHONY : greedy_projection

# fast build rule for target.
greedy_projection/fast:
	$(MAKE) -f CMakeFiles/greedy_projection.dir/build.make CMakeFiles/greedy_projection.dir/build
.PHONY : greedy_projection/fast

#=============================================================================
# Target rules for targets named matrix_transform

# Build rule for target.
matrix_transform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_transform
.PHONY : matrix_transform

# fast build rule for target.
matrix_transform/fast:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/build
.PHONY : matrix_transform/fast

#=============================================================================
# Target rules for targets named normal_estimation

# Build rule for target.
normal_estimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normal_estimation
.PHONY : normal_estimation

# fast build rule for target.
normal_estimation/fast:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/build
.PHONY : normal_estimation/fast

#=============================================================================
# Target rules for targets named pcl_visualizer_demo

# Build rule for target.
pcl_visualizer_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pcl_visualizer_demo
.PHONY : pcl_visualizer_demo

# fast build rule for target.
pcl_visualizer_demo/fast:
	$(MAKE) -f CMakeFiles/pcl_visualizer_demo.dir/build.make CMakeFiles/pcl_visualizer_demo.dir/build
.PHONY : pcl_visualizer_demo/fast

#=============================================================================
# Target rules for targets named resampling

# Build rule for target.
resampling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resampling
.PHONY : resampling

# fast build rule for target.
resampling/fast:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/build
.PHONY : resampling/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

greedy_projection.o: greedy_projection.cpp.o
.PHONY : greedy_projection.o

# target to build an object file
greedy_projection.cpp.o:
	$(MAKE) -f CMakeFiles/greedy_projection.dir/build.make CMakeFiles/greedy_projection.dir/greedy_projection.cpp.o
.PHONY : greedy_projection.cpp.o

greedy_projection.i: greedy_projection.cpp.i
.PHONY : greedy_projection.i

# target to preprocess a source file
greedy_projection.cpp.i:
	$(MAKE) -f CMakeFiles/greedy_projection.dir/build.make CMakeFiles/greedy_projection.dir/greedy_projection.cpp.i
.PHONY : greedy_projection.cpp.i

greedy_projection.s: greedy_projection.cpp.s
.PHONY : greedy_projection.s

# target to generate assembly for a file
greedy_projection.cpp.s:
	$(MAKE) -f CMakeFiles/greedy_projection.dir/build.make CMakeFiles/greedy_projection.dir/greedy_projection.cpp.s
.PHONY : greedy_projection.cpp.s

matrix_transform.o: matrix_transform.cpp.o
.PHONY : matrix_transform.o

# target to build an object file
matrix_transform.cpp.o:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/matrix_transform.cpp.o
.PHONY : matrix_transform.cpp.o

matrix_transform.i: matrix_transform.cpp.i
.PHONY : matrix_transform.i

# target to preprocess a source file
matrix_transform.cpp.i:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/matrix_transform.cpp.i
.PHONY : matrix_transform.cpp.i

matrix_transform.s: matrix_transform.cpp.s
.PHONY : matrix_transform.s

# target to generate assembly for a file
matrix_transform.cpp.s:
	$(MAKE) -f CMakeFiles/matrix_transform.dir/build.make CMakeFiles/matrix_transform.dir/matrix_transform.cpp.s
.PHONY : matrix_transform.cpp.s

normal_estimation_using_integral_images.o: normal_estimation_using_integral_images.cpp.o
.PHONY : normal_estimation_using_integral_images.o

# target to build an object file
normal_estimation_using_integral_images.cpp.o:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/normal_estimation_using_integral_images.cpp.o
.PHONY : normal_estimation_using_integral_images.cpp.o

normal_estimation_using_integral_images.i: normal_estimation_using_integral_images.cpp.i
.PHONY : normal_estimation_using_integral_images.i

# target to preprocess a source file
normal_estimation_using_integral_images.cpp.i:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/normal_estimation_using_integral_images.cpp.i
.PHONY : normal_estimation_using_integral_images.cpp.i

normal_estimation_using_integral_images.s: normal_estimation_using_integral_images.cpp.s
.PHONY : normal_estimation_using_integral_images.s

# target to generate assembly for a file
normal_estimation_using_integral_images.cpp.s:
	$(MAKE) -f CMakeFiles/normal_estimation.dir/build.make CMakeFiles/normal_estimation.dir/normal_estimation_using_integral_images.cpp.s
.PHONY : normal_estimation_using_integral_images.cpp.s

pcl_visualizer_demo.o: pcl_visualizer_demo.cpp.o
.PHONY : pcl_visualizer_demo.o

# target to build an object file
pcl_visualizer_demo.cpp.o:
	$(MAKE) -f CMakeFiles/pcl_visualizer_demo.dir/build.make CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.o
.PHONY : pcl_visualizer_demo.cpp.o

pcl_visualizer_demo.i: pcl_visualizer_demo.cpp.i
.PHONY : pcl_visualizer_demo.i

# target to preprocess a source file
pcl_visualizer_demo.cpp.i:
	$(MAKE) -f CMakeFiles/pcl_visualizer_demo.dir/build.make CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.i
.PHONY : pcl_visualizer_demo.cpp.i

pcl_visualizer_demo.s: pcl_visualizer_demo.cpp.s
.PHONY : pcl_visualizer_demo.s

# target to generate assembly for a file
pcl_visualizer_demo.cpp.s:
	$(MAKE) -f CMakeFiles/pcl_visualizer_demo.dir/build.make CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.s
.PHONY : pcl_visualizer_demo.cpp.s

resampling.o: resampling.cpp.o
.PHONY : resampling.o

# target to build an object file
resampling.cpp.o:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.o
.PHONY : resampling.cpp.o

resampling.i: resampling.cpp.i
.PHONY : resampling.i

# target to preprocess a source file
resampling.cpp.i:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.i
.PHONY : resampling.cpp.i

resampling.s: resampling.cpp.s
.PHONY : resampling.s

# target to generate assembly for a file
resampling.cpp.s:
	$(MAKE) -f CMakeFiles/resampling.dir/build.make CMakeFiles/resampling.dir/resampling.cpp.s
.PHONY : resampling.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... greedy_projection"
	@echo "... matrix_transform"
	@echo "... normal_estimation"
	@echo "... pcl_visualizer_demo"
	@echo "... rebuild_cache"
	@echo "... resampling"
	@echo "... test"
	@echo "... greedy_projection.o"
	@echo "... greedy_projection.i"
	@echo "... greedy_projection.s"
	@echo "... matrix_transform.o"
	@echo "... matrix_transform.i"
	@echo "... matrix_transform.s"
	@echo "... normal_estimation_using_integral_images.o"
	@echo "... normal_estimation_using_integral_images.i"
	@echo "... normal_estimation_using_integral_images.s"
	@echo "... pcl_visualizer_demo.o"
	@echo "... pcl_visualizer_demo.i"
	@echo "... pcl_visualizer_demo.s"
	@echo "... resampling.o"
	@echo "... resampling.i"
	@echo "... resampling.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

